### ISSUE TITLE
Unable to List or Extract Files from Some InstallShield 21 Cabinets

### ISSUE THREAD

**Issue by 6XGate** [twogood/unshield#35] opened 2016-02-03 18:54 UTC
I have tried using _unshield_ on the following cabinet set from InstallShield 21 installers with no luck.

[sp72968.zip](https://github.com/twogood/unshield/files/116199/sp72968.zip)

**Comment by twogood** [comment] 2016-02-03 20:54
Also works fine for me on Linux. Could you please provide some output from unshield?

**Comment by 6XGate** [comment] 2016-02-03 22:37
Same as v15 cabinets;
    > ..\unshield.exe -D 3 l data1.cab
    [unshield_read_headers:226] Reading header from .hdr file 1.
    [unshield_read_headers:262] Failed to read from header file 1. Expected = 45774, read = 1364
    [unshield_open_force_version:363] Failed to read header files
    Failed to open data1.cab as an InstallShield Cabinet File

**Comment by twogood** [comment] 2016-02-04 19:13
Duplicate of #34

**Closed by twogood** 2016-02-04 19:13 UTC
